#指定运行环境
language: node_js

#指定nodejs版本，可以指定多个
node_js:
  - 10

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master

# 缓存目录
cache:
  directories:
    - node_modules

#运行的脚本命令
script:
  - npm run build
  - npm run test

# 收集覆盖率
after_success:
  - npm run report
